export const client = {
  name: "Bob Proctor Fencing",
  tagline: "Professional Fencing Contractor in Newcastle upon Tyne — Quality You Can Trust",
  description: "Professional fencing contractor services in Newcastle upon Tyne and surrounding areas. Trusted local experts with 2 Google reviews.",
  category: "Fencing Contractor",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Newcastle upon Tyne",
  county: "",
  postcode: "",
  basedIn: "Newcastle upon Tyne",
  founderName: "Adam",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "2",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Gavin Lax", rating: 5, text: "Asked Bob to have a look at some fencing and a gate on my fathers property who has dementia. Bob was very understanding and thorough also bang on time. Havent had the job done yet but happy to give Bob the work.", date: "4 years ago", badge: "Local Guide" },
    { name: "sana marfitt-", rating: 5, text: "I called Bob as I have a very heavy garden gate that had come away from its fixings and was pulling bricks out of the garden wall it was attached to. Bob came up with an idea to fix the gate and stop the issue happening in the future, the work was completed at a time that suited me and for a reasonable price, would not hesitate to recommend.", date: "8 years ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Bob Proctor Fencing | Professional Fencing Contractor in Newcastle upon Tyne",
    description: "Professional fencing contractor in Newcastle upon Tyne. 5 stars on Google with 2 reviews. Quality workmanship guaranteed.",
  },
};
